/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SInviteTokenRouteImport } from './routes/s.$inviteToken'
import { Route as AuthenticatedSurveysRouteImport } from './routes/_authenticated/surveys'
import { Route as AuthenticatedAuthenticatedRouteImport } from './routes/_authenticated/authenticated'
import { Route as SInviteTokenCompleteRouteImport } from './routes/s.$inviteToken.complete'
import { Route as AuthenticatedBuilderSurveyIdRouteImport } from './routes/_authenticated/builder.$surveyId'
import { Route as AuthenticatedSurveysSurveyIdInvitesRouteImport } from './routes/_authenticated/surveys.$surveyId.invites'
import { Route as AuthenticatedSurveysSurveyIdBuilderRouteImport } from './routes/_authenticated/surveys.$surveyId.builder'
import { Route as AuthenticatedSurveysSurveyIdAnalyticsRouteImport } from './routes/_authenticated/surveys.$surveyId.analytics'

const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SInviteTokenRoute = SInviteTokenRouteImport.update({
  id: '/s/$inviteToken',
  path: '/s/$inviteToken',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSurveysRoute = AuthenticatedSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuthenticatedRoute =
  AuthenticatedAuthenticatedRouteImport.update({
    id: '/authenticated',
    path: '/authenticated',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const SInviteTokenCompleteRoute = SInviteTokenCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => SInviteTokenRoute,
} as any)
const AuthenticatedBuilderSurveyIdRoute =
  AuthenticatedBuilderSurveyIdRouteImport.update({
    id: '/builder/$surveyId',
    path: '/builder/$surveyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSurveysSurveyIdInvitesRoute =
  AuthenticatedSurveysSurveyIdInvitesRouteImport.update({
    id: '/$surveyId/invites',
    path: '/$surveyId/invites',
    getParentRoute: () => AuthenticatedSurveysRoute,
  } as any)
const AuthenticatedSurveysSurveyIdBuilderRoute =
  AuthenticatedSurveysSurveyIdBuilderRouteImport.update({
    id: '/$surveyId/builder',
    path: '/$surveyId/builder',
    getParentRoute: () => AuthenticatedSurveysRoute,
  } as any)
const AuthenticatedSurveysSurveyIdAnalyticsRoute =
  AuthenticatedSurveysSurveyIdAnalyticsRouteImport.update({
    id: '/$surveyId/analytics',
    path: '/$surveyId/analytics',
    getParentRoute: () => AuthenticatedSurveysRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/surveys': typeof AuthenticatedSurveysRouteWithChildren
  '/s/$inviteToken': typeof SInviteTokenRouteWithChildren
  '/builder/$surveyId': typeof AuthenticatedBuilderSurveyIdRoute
  '/s/$inviteToken/complete': typeof SInviteTokenCompleteRoute
  '/surveys/$surveyId/analytics': typeof AuthenticatedSurveysSurveyIdAnalyticsRoute
  '/surveys/$surveyId/builder': typeof AuthenticatedSurveysSurveyIdBuilderRoute
  '/surveys/$surveyId/invites': typeof AuthenticatedSurveysSurveyIdInvitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/surveys': typeof AuthenticatedSurveysRouteWithChildren
  '/s/$inviteToken': typeof SInviteTokenRouteWithChildren
  '/builder/$surveyId': typeof AuthenticatedBuilderSurveyIdRoute
  '/s/$inviteToken/complete': typeof SInviteTokenCompleteRoute
  '/surveys/$surveyId/analytics': typeof AuthenticatedSurveysSurveyIdAnalyticsRoute
  '/surveys/$surveyId/builder': typeof AuthenticatedSurveysSurveyIdBuilderRoute
  '/surveys/$surveyId/invites': typeof AuthenticatedSurveysSurveyIdInvitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/_authenticated/authenticated': typeof AuthenticatedAuthenticatedRoute
  '/_authenticated/surveys': typeof AuthenticatedSurveysRouteWithChildren
  '/s/$inviteToken': typeof SInviteTokenRouteWithChildren
  '/_authenticated/builder/$surveyId': typeof AuthenticatedBuilderSurveyIdRoute
  '/s/$inviteToken/complete': typeof SInviteTokenCompleteRoute
  '/_authenticated/surveys/$surveyId/analytics': typeof AuthenticatedSurveysSurveyIdAnalyticsRoute
  '/_authenticated/surveys/$surveyId/builder': typeof AuthenticatedSurveysSurveyIdBuilderRoute
  '/_authenticated/surveys/$surveyId/invites': typeof AuthenticatedSurveysSurveyIdInvitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/authenticated'
    | '/surveys'
    | '/s/$inviteToken'
    | '/builder/$surveyId'
    | '/s/$inviteToken/complete'
    | '/surveys/$surveyId/analytics'
    | '/surveys/$surveyId/builder'
    | '/surveys/$surveyId/invites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/authenticated'
    | '/surveys'
    | '/s/$inviteToken'
    | '/builder/$surveyId'
    | '/s/$inviteToken/complete'
    | '/surveys/$surveyId/analytics'
    | '/surveys/$surveyId/builder'
    | '/surveys/$surveyId/invites'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/callback'
    | '/_authenticated/authenticated'
    | '/_authenticated/surveys'
    | '/s/$inviteToken'
    | '/_authenticated/builder/$surveyId'
    | '/s/$inviteToken/complete'
    | '/_authenticated/surveys/$surveyId/analytics'
    | '/_authenticated/surveys/$surveyId/builder'
    | '/_authenticated/surveys/$surveyId/invites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  SInviteTokenRoute: typeof SInviteTokenRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$inviteToken': {
      id: '/s/$inviteToken'
      path: '/s/$inviteToken'
      fullPath: '/s/$inviteToken'
      preLoaderRoute: typeof SInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/surveys': {
      id: '/_authenticated/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof AuthenticatedSurveysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/authenticated': {
      id: '/_authenticated/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedAuthenticatedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/s/$inviteToken/complete': {
      id: '/s/$inviteToken/complete'
      path: '/complete'
      fullPath: '/s/$inviteToken/complete'
      preLoaderRoute: typeof SInviteTokenCompleteRouteImport
      parentRoute: typeof SInviteTokenRoute
    }
    '/_authenticated/builder/$surveyId': {
      id: '/_authenticated/builder/$surveyId'
      path: '/builder/$surveyId'
      fullPath: '/builder/$surveyId'
      preLoaderRoute: typeof AuthenticatedBuilderSurveyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/surveys/$surveyId/invites': {
      id: '/_authenticated/surveys/$surveyId/invites'
      path: '/$surveyId/invites'
      fullPath: '/surveys/$surveyId/invites'
      preLoaderRoute: typeof AuthenticatedSurveysSurveyIdInvitesRouteImport
      parentRoute: typeof AuthenticatedSurveysRoute
    }
    '/_authenticated/surveys/$surveyId/builder': {
      id: '/_authenticated/surveys/$surveyId/builder'
      path: '/$surveyId/builder'
      fullPath: '/surveys/$surveyId/builder'
      preLoaderRoute: typeof AuthenticatedSurveysSurveyIdBuilderRouteImport
      parentRoute: typeof AuthenticatedSurveysRoute
    }
    '/_authenticated/surveys/$surveyId/analytics': {
      id: '/_authenticated/surveys/$surveyId/analytics'
      path: '/$surveyId/analytics'
      fullPath: '/surveys/$surveyId/analytics'
      preLoaderRoute: typeof AuthenticatedSurveysSurveyIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedSurveysRoute
    }
  }
}

interface AuthenticatedSurveysRouteChildren {
  AuthenticatedSurveysSurveyIdAnalyticsRoute: typeof AuthenticatedSurveysSurveyIdAnalyticsRoute
  AuthenticatedSurveysSurveyIdBuilderRoute: typeof AuthenticatedSurveysSurveyIdBuilderRoute
  AuthenticatedSurveysSurveyIdInvitesRoute: typeof AuthenticatedSurveysSurveyIdInvitesRoute
}

const AuthenticatedSurveysRouteChildren: AuthenticatedSurveysRouteChildren = {
  AuthenticatedSurveysSurveyIdAnalyticsRoute:
    AuthenticatedSurveysSurveyIdAnalyticsRoute,
  AuthenticatedSurveysSurveyIdBuilderRoute:
    AuthenticatedSurveysSurveyIdBuilderRoute,
  AuthenticatedSurveysSurveyIdInvitesRoute:
    AuthenticatedSurveysSurveyIdInvitesRoute,
}

const AuthenticatedSurveysRouteWithChildren =
  AuthenticatedSurveysRoute._addFileChildren(AuthenticatedSurveysRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAuthenticatedRoute: typeof AuthenticatedAuthenticatedRoute
  AuthenticatedSurveysRoute: typeof AuthenticatedSurveysRouteWithChildren
  AuthenticatedBuilderSurveyIdRoute: typeof AuthenticatedBuilderSurveyIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuthenticatedRoute: AuthenticatedAuthenticatedRoute,
  AuthenticatedSurveysRoute: AuthenticatedSurveysRouteWithChildren,
  AuthenticatedBuilderSurveyIdRoute: AuthenticatedBuilderSurveyIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SInviteTokenRouteChildren {
  SInviteTokenCompleteRoute: typeof SInviteTokenCompleteRoute
}

const SInviteTokenRouteChildren: SInviteTokenRouteChildren = {
  SInviteTokenCompleteRoute: SInviteTokenCompleteRoute,
}

const SInviteTokenRouteWithChildren = SInviteTokenRoute._addFileChildren(
  SInviteTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  SInviteTokenRoute: SInviteTokenRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
